### ISSUE TITLE
Query a different datacenter

### ISSUE THREAD

**Issue by pvyaka01** [StackStorm-Exchange/stackstorm-consul#29]
I've a situation where stackstorm is centralized and i need to make queries to consul to get nodes and such from multiple data centers. How do we go about it? If I pass dc="<value>" it won't work because it doesn't know anything about that dc. Any ideas? 

I'd guess this is a typical setup where we won't have StackStorm setup in each environment.

Thanks for any insight!

**Comment by nzlosh** [comment]
If each dc has a separate consul cluster instance, you could configure the pack to have a consul profile per dc.  Each action accepts a profile as a parameter, so you could specify which dc to use like that.

**Comment by pvyaka01** [comment]
Thank you, that worked.

**Comment by nzlosh** [comment]
Good to hear.
